db:
  connection: "{url:'htpp://newly updated-prod-env_____', username:'myname-prod', password:'pass123-prod'}"
  port: 1234
  host: 0.123.01

credentials:
  username: newly update myname
  password: newly updated mypass123
